name: 'RaspberryPiPicoBuild'
description: 'Sets up action pipeline for building a Pico SDK project'

runs:
  using: "composite"
  steps:
    - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1.5.2
      shell: bash
    - name: Checkout pico-sdk/1.5.0
      uses: actions/checkout@v3
      with:
        repository: raspberrypi/pico-sdk
        ref: 1.5.0
        path: pico-sdk
      shell: bash
    - name: Checkout pico-sdk submodules
      working-directory: ${{github.workspace}}/pico-sdk
      run: git submodule update --init
      shell: bash
